import { useState, useEffect } from 'react';
import { useApp } from '@/context/AppContext';
import { PageShell } from '@/components/Nav';
import { PillButton } from '@/components/PillButton';
import { Modal } from '@/components/Modal';
import { getPostTypeMeta } from '@/data/postTypes';
import {
  MessageSquare, Clock, CheckCircle2, Users, ArrowRight,
  FileText, Play, Sparkles, MessagesSquare, Download, Eye, X,
  Target, AlertCircle,
} from 'lucide-react';
import type { ConversationSession, ConversationSummary, PostType } from '@/data/types';

type SubTab = 'active' | 'completed';

export function ConversationsPage() {
  const { conversations, posts, navigate, conversationSummaries } = useApp();
  const [subTab, setSubTab] = useState<SubTab>('active');
  const [viewingSummary, setViewingSummary] = useState<ConversationSummary | null>(null);

  const activeConversations = conversations.filter((c) => c.status === 'active');
  const completedConversations = conversations.filter((c) => c.status === 'completed');

  const handleExportSummary = (summary: ConversationSummary) => {
    const lines: string[] = [];
    lines.push('========================================');
    lines.push('   AI CONVERSATION SUMMARY');
    lines.push('========================================');
    lines.push('');
    lines.push(`Conversation Title: ${summary.postTitle}`);
    lines.push(`Date: ${summary.date ?? new Date(summary.createdAt).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}`);
    if (summary.durationMinutes) lines.push(`Duration: ${summary.durationMinutes} minutes`);
    lines.push(`Participants: ${summary.participants.join(', ')}`);
    lines.push('');
    lines.push('--- SUMMARY ---');
    lines.push(summary.summary);
    lines.push('');
    if (summary.mainTopic) {
      lines.push('--- MAIN TOPIC ---');
      lines.push(summary.mainTopic);
      lines.push('');
    }
    if (summary.skillsDiscussed && summary.skillsDiscussed.length > 0) {
      lines.push('--- SKILLS DISCUSSED ---');
      summary.skillsDiscussed.forEach((s) => lines.push(`  - ${s}`));
      lines.push('');
    }
    if (summary.keyPoints.length > 0) {
      lines.push('--- KEY DISCUSSION POINTS ---');
      summary.keyPoints.forEach((p) => lines.push(`  - ${p}`));
      lines.push('');
    }
    if (summary.collaborationAreas && summary.collaborationAreas.length > 0) {
      lines.push('--- POTENTIAL COLLABORATION AREAS ---');
      summary.collaborationAreas.forEach((c) => lines.push(`  - ${c}`));
      lines.push('');
    }
    if (summary.decisions && summary.decisions.length > 0) {
      lines.push('--- DECISIONS / AGREEMENTS ---');
      summary.decisions.forEach((d) => lines.push(`  - ${d}`));
      lines.push('');
    }
    if (summary.actionItems.length > 0) {
      lines.push('--- TASKS / RESPONSIBILITIES ---');
      summary.actionItems.forEach((a) => lines.push(`  - ${a}`));
      lines.push('');
    }
    if (summary.deadlines && summary.deadlines.length > 0) {
      lines.push('--- DEADLINES MENTIONED ---');
      summary.deadlines.forEach((d) => lines.push(`  - ${d}`));
      lines.push('');
    }
    if (summary.unresolvedPoints && summary.unresolvedPoints.length > 0) {
      lines.push('--- UNRESOLVED POINTS ---');
      summary.unresolvedPoints.forEach((u) => lines.push(`  - ${u}`));
      lines.push('');
    }
    if (summary.nextSteps && summary.nextSteps.length > 0) {
      lines.push('--- NEXT STEPS ---');
      summary.nextSteps.forEach((n) => lines.push(`  - ${n}`));
      lines.push('');
    }
    lines.push('========================================');
    lines.push(`Generated by GlobalStudent AI Assistant`);
    lines.push(`Exported: ${new Date().toLocaleString()}`);
    lines.push('========================================');

    const blob = new Blob([lines.join('\n')], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `conversation-summary-${summary.postTitle.replace(/[^a-z0-9]/gi, '-').toLowerCase()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <PageShell title="Conversations">
      <div className="mx-auto max-w-4xl">
        {/* Sub-tabs */}
        <div className="mb-6 flex gap-1.5 rounded-card-lg bg-white p-1.5 shadow-soft">
          <SubTabButton
            active={subTab === 'active'}
            onClick={() => setSubTab('active')}
            icon={<Play size={16} />}
            label="Active Conversations"
            count={activeConversations.length}
            activeColor="bg-sage-500"
          />
          <SubTabButton
            active={subTab === 'completed'}
            onClick={() => setSubTab('completed')}
            icon={<CheckCircle2 size={16} />}
            label="Completed Conversations"
            count={completedConversations.length}
            activeColor="bg-lavender-500"
          />
        </div>

        {subTab === 'active' && (
          <div className="space-y-3">
            {activeConversations.length === 0 ? (
              <div className="flex flex-col items-center justify-center rounded-card-lg bg-white py-20 text-center shadow-card">
                <div className="mb-4 flex h-16 w-16 items-center justify-center rounded-full bg-cream-200">
                  <MessagesSquare className="text-navy-400/40" size={32} />
                </div>
                <p className="font-display text-lg font-bold text-navy-500">No active conversations</p>
                <p className="mt-1 text-sm text-navy-400">Start a conversation from any project post or peer profile</p>
                <div className="mt-5 flex gap-3">
                  <PillButton variant="primary" onClick={() => navigate({ name: 'home' })}>
                    Browse Posts
                  </PillButton>
                  <PillButton variant="teal" onClick={() => navigate({ name: 'find-students' })}>
                    Find Students
                  </PillButton>
                </div>
              </div>
            ) : (
              activeConversations.map((conv) => (
                <ConversationCard
                  key={conv.id}
                  conversation={conv}
                  post={posts.find((p) => p.id === conv.postId)}
                  onEnter={() => navigate({ name: 'activity-chat', postId: conv.postId })}
                  onWorkspace={() => navigate({ name: 'team-workspace', postId: conv.postId })}
                />
              ))
            )}
          </div>
        )}

        {subTab === 'completed' && (
          <div className="space-y-3">
            {completedConversations.length === 0 ? (
              <div className="flex flex-col items-center justify-center rounded-card-lg bg-white py-20 text-center shadow-card">
                <div className="mb-3 flex h-16 w-16 items-center justify-center rounded-full bg-cream-200">
                  <CheckCircle2 className="text-navy-400/40" size={32} />
                </div>
                <p className="font-display text-lg font-bold text-navy-500">No completed conversations yet</p>
                <p className="mt-1 text-sm text-navy-400">Conversations will appear here after their timer ends</p>
              </div>
            ) : (
              completedConversations.map((conv) => {
                const summary = conversationSummaries.find((s) => s.postId === conv.postId);
                return (
                  <CompletedConversationCard
                    key={conv.id}
                    conversation={conv}
                    post={posts.find((p) => p.id === conv.postId)}
                    summary={summary}
                    onWorkspace={() => navigate({ name: 'team-workspace', postId: conv.postId })}
                    onPostDetail={() => navigate({ name: 'post-detail', postId: conv.postId })}
                    onViewSummary={() => summary && setViewingSummary(summary)}
                    onExportSummary={() => summary && handleExportSummary(summary)}
                  />
                );
              })
            )}
          </div>
        )}
      </div>

      {/* View AI Summary Modal */}
      <Modal
        open={!!viewingSummary}
        onClose={() => setViewingSummary(null)}
        title="AI Conversation Summary"
      >
        {viewingSummary && <FullSummaryView summary={viewingSummary} onExport={() => handleExportSummary(viewingSummary)} />}
      </Modal>
    </PageShell>
  );
}

function FullSummaryView({ summary, onExport }: { summary: ConversationSummary; onExport: () => void }) {
  return (
    <div className="space-y-4">
      {/* Header info */}
      <div className="grid grid-cols-2 gap-3">
        <div className="rounded-btn bg-cream-50 p-3">
          <p className="text-xs font-bold uppercase text-navy-400">Date</p>
          <p className="text-sm font-bold text-navy-500">{summary.date ?? new Date(summary.createdAt).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}</p>
        </div>
        {summary.durationMinutes && (
          <div className="rounded-btn bg-cream-50 p-3">
            <p className="text-xs font-bold uppercase text-navy-400">Duration</p>
            <p className="text-sm font-bold text-navy-500">{summary.durationMinutes} minutes</p>
          </div>
        )}
      </div>

      {/* Participants */}
      <div>
        <p className="mb-1 text-xs font-bold uppercase text-navy-400">Participants</p>
        <div className="flex flex-wrap gap-2">
          {summary.participants.map((p) => (
            <span key={p} className="rounded-btn bg-lavender-200 px-2.5 py-1 text-xs font-bold text-navy-500">{p}</span>
          ))}
        </div>
      </div>

      {/* Summary text */}
      <div className="rounded-btn bg-cream-50 p-3">
        <p className="text-sm font-semibold text-navy-500">{summary.summary}</p>
      </div>

      {/* Main topic */}
      {summary.mainTopic && (
        <SummarySection title="Main Topic" icon={<Target size={14} />} items={[summary.mainTopic]} />
      )}

      {/* Skills discussed */}
      {summary.skillsDiscussed && summary.skillsDiscussed.length > 0 && (
        <div>
          <p className="mb-1 flex items-center gap-1.5 text-xs font-bold uppercase text-navy-400"><Sparkles size={14} className="text-lavender-500" /> Skills Discussed</p>
          <div className="flex flex-wrap gap-1.5">
            {summary.skillsDiscussed.map((s) => (
              <span key={s} className="rounded-btn bg-sky-300/50 px-2 py-0.5 text-xs font-bold text-sky-600">{s}</span>
            ))}
          </div>
        </div>
      )}

      {/* Key points */}
      {summary.keyPoints.length > 0 && (
        <SummarySection title="Key Discussion Points" icon={<CheckCircle2 size={14} />} items={summary.keyPoints} />
      )}

      {/* Collaboration areas */}
      {summary.collaborationAreas && summary.collaborationAreas.length > 0 && (
        <SummarySection title="Potential Collaboration Areas" icon={<Users size={14} />} items={summary.collaborationAreas} />
      )}

      {/* Decisions */}
      {summary.decisions && summary.decisions.length > 0 && (
        <SummarySection title="Decisions / Agreements" icon={<CheckCircle2 size={14} />} items={summary.decisions} />
      )}

      {/* Action items */}
      {summary.actionItems.length > 0 && (
        <SummarySection title="Tasks / Responsibilities" icon={<ArrowRight size={14} />} items={summary.actionItems} />
      )}

      {/* Deadlines */}
      {summary.deadlines && summary.deadlines.length > 0 && (
        <SummarySection title="Deadlines Mentioned" icon={<Clock size={14} />} items={summary.deadlines} />
      )}

      {/* Unresolved points */}
      {summary.unresolvedPoints && summary.unresolvedPoints.length > 0 && (
        <SummarySection title="Unresolved Points" icon={<AlertCircle size={14} />} items={summary.unresolvedPoints} />
      )}

      {/* Next steps */}
      {summary.nextSteps && summary.nextSteps.length > 0 && (
        <SummarySection title="Next Steps" icon={<ArrowRight size={14} />} items={summary.nextSteps} />
      )}

      <div className="flex justify-end pt-2">
        <PillButton variant="primary" onClick={onExport}>
          <Download size={16} /> Export Summary
        </PillButton>
      </div>
    </div>
  );
}

function SummarySection({ title, icon, items }: { title: string; icon: React.ReactNode; items: string[] }) {
  return (
    <div>
      <p className="mb-1 flex items-center gap-1.5 text-xs font-bold uppercase text-navy-400">{icon} {title}</p>
      <ul className="space-y-1">
        {items.map((item, i) => (
          <li key={i} className="flex items-start gap-1.5 text-sm font-semibold text-navy-500">
            <span className="text-navy-400/40 shrink-0 mt-0.5">·</span> {item}
          </li>
        ))}
      </ul>
    </div>
  );
}

function SubTabButton({
  active, onClick, icon, label, count, activeColor,
}: {
  active: boolean;
  onClick: () => void;
  icon: React.ReactNode;
  label: string;
  count: number;
  activeColor: string;
}) {
  return (
    <button
      onClick={onClick}
      className={`flex flex-1 items-center justify-center gap-2 rounded-btn px-4 py-3 text-sm font-bold transition ${
        active ? `${activeColor} text-white shadow-soft` : 'text-navy-400 hover:bg-cream-200'
      }`}
    >
      {icon}
      <span className="hidden sm:inline">{label}</span>
      <span className="inline sm:hidden">{label.split(' ')[0]}</span>
      {count > 0 && (
        <span className={`rounded-full px-2 text-xs font-bold ${active ? 'bg-white/25 text-white' : 'bg-cream-300 text-navy-500'}`}>
          {count}
        </span>
      )}
    </button>
  );
}

function ConversationCard({
  conversation, post, onEnter, onWorkspace,
}: {
  conversation: ConversationSession;
  post?: { type: PostType; title: string };
  onEnter: () => void;
  onWorkspace: () => void;
}) {
  const meta = post ? getPostTypeMeta(post.type) : null;
  const [, setTick] = useState(0);

  useEffect(() => {
    const interval = setInterval(() => setTick((t) => t + 1), 1000);
    return () => clearInterval(interval);
  }, []);

  const startTime = new Date(conversation.startedAt);
  const elapsed = Math.floor((Date.now() - startTime.getTime()) / 1000);
  const total = conversation.durationMinutes * 60;
  const remaining = Math.max(0, total - elapsed);
  const remainingMins = Math.floor(remaining / 60);
  const remainingSecs = remaining % 60;
  const isEndingSoon = remaining <= 120 && remaining > 0;
  const isExpired = remaining <= 0;

  return (
    <div className="rounded-card-lg bg-white p-5 shadow-card transition hover:shadow-pop">
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div className="flex items-start gap-3">
          {meta && (
            <div className={`flex h-10 w-10 items-center justify-center rounded-btn ${meta.bgColor} text-lg shrink-0`}>
              {meta.icon}
            </div>
          )}
          <div>
            <h3 className="font-display text-base font-bold text-navy-500">{conversation.postTitle}</h3>
            <p className="text-xs font-semibold text-navy-400 mt-0.5">{conversation.purpose}</p>
            <div className="mt-2 flex flex-wrap items-center gap-3 text-xs font-semibold text-navy-400">
              <span className="flex items-center gap-1">
                <Users size={12} /> {conversation.participantNames.join(', ')}
              </span>
              <span className={`flex items-center gap-1 rounded-pill px-2 py-0.5 ${
                isExpired ? 'bg-poppy-300 text-poppy-700' :
                isEndingSoon ? 'bg-peach-300 text-peach-700' : 'bg-sage-300 text-sage-700'
              }`}>
                <Clock size={12} /> {isExpired ? 'Ended' : `${String(remainingMins).padStart(2, '0')}:${String(remainingSecs).padStart(2, '0')} left`}
              </span>
              <span className="text-navy-400/70">{conversation.durationMinutes} min session</span>
            </div>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <PillButton variant="primary" size="sm" onClick={onEnter}>
            <MessageSquare size={14} /> Resume
          </PillButton>
          <PillButton variant="teal" size="sm" onClick={onWorkspace}>
            Workspace
          </PillButton>
        </div>
      </div>
    </div>
  );
}

function CompletedConversationCard({
  conversation, post, summary, onWorkspace, onPostDetail, onViewSummary, onExportSummary,
}: {
  conversation: ConversationSession;
  post?: { type: PostType };
  summary?: ConversationSummary;
  onWorkspace: () => void;
  onPostDetail: () => void;
  onViewSummary: () => void;
  onExportSummary: () => void;
}) {
  const meta = post ? getPostTypeMeta(post.type) : null;
  const endedAt = conversation.endedAt ? new Date(conversation.endedAt) : null;

  return (
    <div className="rounded-card-lg bg-white p-5 shadow-card">
      <div className="flex items-start gap-3 mb-3">
        {meta && (
          <div className={`flex h-10 w-10 items-center justify-center rounded-btn ${meta.bgColor} text-lg shrink-0`}>
            {meta.icon}
          </div>
        )}
        <div className="flex-1">
          <div className="flex items-center gap-2 flex-wrap">
            <h3 className="font-display text-base font-bold text-navy-500">{conversation.postTitle}</h3>
            <span className="rounded-pill bg-lavender-300/50 px-2 py-0.5 text-xs font-bold text-lavender-700">Completed</span>
          </div>
          <p className="text-xs font-semibold text-navy-400 mt-0.5">{conversation.purpose}</p>
          <div className="mt-1 flex flex-wrap items-center gap-3 text-xs font-semibold text-navy-400">
            <span className="flex items-center gap-1">
              <Clock size={12} /> {conversation.durationMinutes} min
            </span>
            <span className="flex items-center gap-1">
              <Users size={12} /> {conversation.participantNames.join(', ')}
            </span>
            {endedAt && (
              <span>Ended {endedAt.toLocaleDateString('en-US', { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' })}</span>
            )}
          </div>
        </div>
      </div>

      {/* Final response */}
      {conversation.finalResponse && (
        <div className="mb-3 rounded-btn bg-cream-50 p-3">
          <p className="text-xs font-bold uppercase text-navy-400 mb-1">Final Response Sent</p>
          <p className="text-sm font-semibold text-navy-500 text-right" dir="rtl">{conversation.finalResponse}</p>
        </div>
      )}

      {/* AI Summary preview */}
      {summary && (
        <div className="mb-3 rounded-btn border-2 border-lavender-300/60 bg-lavender-200/10 p-3">
          <div className="mb-2 flex items-center gap-1.5">
            <Sparkles size={14} className="text-lavender-600" />
            <p className="text-xs font-bold text-lavender-700">AI Conversation Summary</p>
          </div>
          <p className="text-xs font-semibold text-navy-500 mb-2">{summary.summary}</p>
          {summary.keyPoints.length > 0 && (
            <div className="mb-2">
              <p className="text-[10px] font-bold uppercase text-navy-400 mb-0.5">Key Points</p>
              <ul className="space-y-0.5">
                {summary.keyPoints.slice(0, 3).map((kp, i) => (
                  <li key={i} className="flex items-start gap-1 text-xs font-semibold text-navy-500">
                    <CheckCircle2 size={10} className="text-sage-500 mt-0.5 shrink-0" /> {kp}
                  </li>
                ))}
              </ul>
            </div>
          )}
        </div>
      )}

      <div className="flex flex-wrap items-center gap-2">
        <PillButton variant="teal" size="sm" onClick={onWorkspace}>
          <FileText size={14} /> Team Workspace
        </PillButton>
        {summary && (
          <>
            <PillButton variant="navy" size="sm" onClick={onViewSummary}>
              <Eye size={14} /> View AI Summary
            </PillButton>
            <PillButton variant="white" size="sm" onClick={onExportSummary}>
              <Download size={14} /> Export
            </PillButton>
          </>
        )}
        <PillButton variant="white" size="sm" onClick={onPostDetail}>
          View Post
        </PillButton>
      </div>
    </div>
  );
}
